### ISSUE TITLE
Should data.json have something to let explorer sort versions into order?

### ISSUE THREAD

**Issue by ghost** [open-contracting/extensions-data-collector#16]
Currently it has for each extension:

    { "name":"extension", ,,,, "versions": { "master": {...}, "v1.0.0": {...}, "v1.1.0": {...} }

However being unsorted, if you get all the keys in the versions array you may get

    ["master", "v1.0.0", "v1.1.0"]

one time and 

    [ "v1.1.0", "master", "v1.0.0"]

another time.

When building the website, we probably want the versions listed in a consistent order each time. Could the collector add some data to help with that?

Maybe extensions could have:
 
    { "name":"extension", , , ,, ,, "version_keys_ordered": [ "master", "v1.0.0", "v1.1.0" ] }

Or have a separation between semver and non semver, In case the website wants to present them differently?

    { "name":"extension", , , ,, ,, "semver_version_keys_ordered": [ "v1.0.0", "v1.1.0" ], "none_semver_version_keys_ordered": [ "master" ] }

@kindly

**Comment by jpmckinney** [comment]
The registry provides a `Date` for 'frozen' releases. One option is for applications to sort by Date and then by Version.

**Comment by ghost** [comment]
Conversation with @kindly: 

If we can get ordered JSON out, with the "versions" data in the right order that would be cool.

But I'll also add some keys to the data. As this is a library, other people may be consuming the data and we want to make it totally simple and robust for them.

**Comment by ghost** [comment]
First attempt at this done, adds a basic key.

Should try and do the ordered JSON thing, and also discuss further with @kindly the best way of doing this.

**Comment by jpmckinney** [comment]
The extension registry CSV already sorts versions in one of many possible, reasonable orders: `master`, followed by frozen versions in chronological order (the same order as in above commit).

If applications want to re-sort versions, they can do so using e.g. the Date of the version, or other metadata available in the file.

I'm removing the key, as almost all JSON implementations have the option of keeping order when reading data, and users need to be reading the file with that option, as otherwise, for example, codelist fieldnames and rows will be read in the incorrect order.

Closing as the present solution is sufficient.
