### ISSUE TITLE
Code versioning and documentation around #25

### ISSUE THREAD

**Issue by ghost** [open-contracting/extensions-data-collector#28]
Hello @jpmckinney,

I had a look at this pull request as it causes some problems for us. The basic root problem is that this library isn’t versioned or documented properly, yet it is already in use in other places. 

Therefore any changes that break backwards compatibility cause problems elsewhere; specifically:

1)

The Extension Explorer project expects the data input to be in a certain format, and this changes some of the structure. This now means the extension explorer site is broken. When looking at any extension, I now get:

AttributeError: 'str' object has no attribute 'get'
 
2)

Our dev site showing the extension explorer site is still ok, but that’s due to an fortunate accident. This removes “requirements.txt” and the build process expects that to be there, so the build process is broken. This means the old site and data from before the changes is still showing.

As this is a library, we should be both versioning and documenting changes properly. Then users of the library can both lock to a specific version and know what has changed when they come to upgrade.

Generally, we are trying to increase the amount of documentation - as we have more developers it really helps (we’re looking forward to working with the new people in ILDA), and it really helps existing developers too! We are frequently switching between projects and tasks within those projects, and being able to read something to refresh your mind really helps. 

As part of that, we are trying to run a CHANGELOG file in each library repository like this one; there is currently one but we haven’t actually started it yet! It would be good to start that now and make sure any changes are listed. This will help us and other developers to stay up to speed when we’re changing between working on different projects.

So can I suggest; we tag version 0.1.0 of this at commit a8056dd253e2ae2ffd7ed1dfacc7af481d102d4b - this is the last commit we knew about on master.

We will then lock our use of the library in the dev site to 0.1.0, which should make it work again.

We’d then ask you to write a full changelog and an updated readme with everything you’ve just done and merged in, and tag that as version 0.2.0.

We will need that changelog documentation so we know what has changed when we come to upgrade the website to use version 0.2.0 - I don’t know when that will be scheduled for but that will take us some time at some point, due to the backwards incompatible breaks.

How does that sound?
Thanks,
James

**Comment by jpmckinney** [comment]
(1) I was only aware of the extension explorer being dependent on this repo. What else depends on it? I'm updating both this project and the extension explorer; I have a local copy of the extension explorer that works with the changes, which I'll push once I'm done making changes to this project.

With respect to any broken compatibility in other tools, can't those tools simply refer to a specific git commit, instead of HEAD? Those tools can later be updated to use HEAD if needed. (I agree that referring to versions is better than referring to commits, but this project isn't versioned yet.)

(2) My understanding from my call with @robredpath was that there wasn't yet an automated build of the extension explorer, and that the dev deployment had been a manual build. If there is a build process, please document it, as otherwise I can't account for it. (The build process shouldn't involve pulling the latest version of the collector; changing dependencies should require a re-deploy.)

Regarding versioning, I agree. However, given that neither this project nor the extension explorer are in production or advertised, I have been treating them as 'in development' and therefore subject to any change without public notice through a changelog. The file format, for example, hasn't been documented, which is something I'll do as part of these updates (along with tagging releases).

----

The changes I've made recently include:

* Moving/adding more functionality to extension_registry.py from this project and documentation-support, briefly documented in its [changelog](https://github.com/open-contracting/extension_registry.py/blob/master/CHANGELOG.md), and which I'll document further in the readme. There is also a [ReadTheDocs website](https://ocdsextensionregistry.readthedocs.io/en/latest/api/extension_version.html), though I just noticed I forgot to add new classes to the toctree https://github.com/open-contracting/extension_registry.py/pull/13.
* Creating a new repository, ocds-babel, to centralize all extraction and translation methods, from this project and documentation-support. It also has a changelog and a ReadTheDocs website, though I have to fix the automodule directive https://github.com/open-contracting/ocds-babel/pull/3.
* Removing documentation-support, which no longer had distinct functionality from extension_registry.py or ocds-babel.

Essentially, the changes have been to centralize responsibility for extensions/registry and extraction/translation into two libraries, instead of having code spread around an increasing number of repositories, with inconsistent or inaccessible APIs, making re-use difficult.

Through this work, the collector is also becoming increasingly thin, and may end up being merged into extension_registry.py as its CLI.

Anyhow, I'm actively working on this and the explorer, and since the dev deployment isn't broken, I think it's simplest for me to complete the work, rather than tag and release a library which may end up being merged into another library.

**Comment by jpmckinney** [comment]
Let's continue the discussion via email or CRM. I'm closing this issue, as I am archiving this repository, after copying / moving functionality to extension_registry.py. https://github.com/open-contracting/extension_registry.py/pull/18
